#!/usr/bin/env python3
"""Bake the Globe screen's Earth map into flash: src/globe_texture.h + src/globe_texture.c.

Source: the three.js example planet textures that Doug's homepage globe uses (and that
~/Claude/planets vendors as assets/tex/earth.jpg, byte-identical):

    earth_atmos_2048.jpg     2048x1024 colour map
    earth_clouds_1024.png    1024x512  cloud layer (alpha)
    earth_specular_2048.jpg  2048x1024 ocean mask (white = water)

These are from the three.js repository (MIT licence), and are themselves derived from
NASA Visible Earth / Blue Marble imagery (public domain). See ~/Claude/planets/CREDITS.md.

What comes out (all const, so it stays in flash):

    globe_tex[256][512]    RGB565, equirectangular, row 0 = 90N, column 0 = 180W
    globe_ocean[256][64]   1 bit per texel, bit (u & 7) of byte u >> 3: 1 = water

Why 512x256: the screen renders the globe at half resolution, 96 px radius, so the
centre of the disc shows ~1.36 render px per degree of longitude. 512 columns is 1.42
per degree: one texel per rendered pixel where the globe is sharpest, and more than
enough towards the limb, where everything is foreshortened. 1024x512 would cost 1 MB
for detail the 233 px frame cannot show. 256 KB + 16 KB here.

The texture is pre-treated so that the device can shade it with a single multiply and
still look like the homepage. The homepage (three.js r165) loads the map without a
colour space, so its bytes are used as LINEAR values, lit, then sRGB-encoded on output:
out = srgb(t * k). With a power-law approximation that is srgb(t) * srgb(k), so this
bakes srgb(t) (and blends the clouds in that space, as the page's blending does) and
the device multiplies by a per-pixel shade that already holds srgb(k).

Usage:
    python3 tools/bake_globe_texture.py [texture dir]   (default ~/Claude/homepage/assets/textures)
Needs Pillow.
"""
import os
import sys

from PIL import Image

W, H = 512, 256
CLOUD_OPACITY = 0.38          # the homepage's cloud mesh opacity
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, '..', 'src', 'globe_texture.h')
OUT_C = os.path.join(HERE, '..', 'src', 'globe_texture.c')

BAYER4 = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]


def srgb(x):
    x = max(0.0, min(1.0, x))
    return 12.92 * x if x <= 0.0031308 else 1.055 * x ** (1 / 2.4) - 0.055


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Claude/homepage/assets/textures')
    atmos = Image.open(os.path.join(src, 'earth_atmos_2048.jpg')).convert('RGB')
    clouds = Image.open(os.path.join(src, 'earth_clouds_1024.png')).convert('RGBA')
    spec = Image.open(os.path.join(src, 'earth_specular_2048.jpg')).convert('L')

    atmos = atmos.resize((W, H), Image.LANCZOS)
    clouds = clouds.resize((W, H), Image.LANCZOS)
    spec = spec.resize((W, H), Image.BOX)

    enc = [srgb(i / 255.0) for i in range(256)]
    A = atmos.load()
    C = clouds.load()
    S = spec.load()

    tex = []
    ocean = bytearray(W * H // 8)
    for v in range(H):
        for u in range(W):
            r, g, b = A[u, v]
            cr, cg, cb, ca = C[u, v]
            a = CLOUD_OPACITY * ca / 255.0
            rgb = [(1 - a) * enc[r] + a * enc[cr],
                   (1 - a) * enc[g] + a * enc[cg],
                   (1 - a) * enc[b] + a * enc[cb]]
            # ordered dither into 5/6/5 bits: the oceans are wide flat gradients
            d = (BAYER4[v & 3][u & 3] + 0.5) / 16.0
            R = min(31, int(rgb[0] * 31 + d))
            G = min(63, int(rgb[1] * 63 + d))
            B = min(31, int(rgb[2] * 31 + d))
            tex.append((R << 11) | (G << 5) | B)
            if S[u, v] >= 128:
                ocean[(v * W + u) >> 3] |= 1 << (u & 7)

    with open(OUT_H, 'w') as f:
        f.write('#pragma once\n')
        f.write('// Generated by tools/bake_globe_texture.py. Do not edit.\n')
        f.write('// Earth map for the Globe screen: three.js example textures (MIT), from NASA\n')
        f.write('// Visible Earth / Blue Marble (public domain). See the script for the treatment.\n')
        f.write('#include <stdint.h>\n\n')
        f.write('#define GLOBE_TEX_W %d\n#define GLOBE_TEX_H %d\n\n' % (W, H))
        f.write('#ifdef __cplusplus\nextern "C" {\n#endif\n')
        f.write('extern const uint16_t globe_tex[GLOBE_TEX_W * GLOBE_TEX_H];     // RGB565, row 0 = 90N, col 0 = 180W\n')
        f.write('extern const uint8_t  globe_ocean[GLOBE_TEX_W * GLOBE_TEX_H / 8]; // 1 = water; bit (u & 7) of byte (v*W+u) >> 3\n')
        f.write('#ifdef __cplusplus\n}\n#endif\n')

    with open(OUT_C, 'w') as f:
        f.write('// Generated by tools/bake_globe_texture.py. Do not edit.\n')
        f.write('// Source: three.js examples/textures/planets earth_atmos_2048.jpg, earth_clouds_1024.png,\n')
        f.write('// earth_specular_2048.jpg (MIT licence), derived from NASA Visible Earth / Blue Marble\n')
        f.write('// (public domain). %dx%d RGB565, sRGB-treated, clouds blended at %.2f.\n' % (W, H, CLOUD_OPACITY))
        f.write('#include "globe_texture.h"\n\n')
        f.write('const uint16_t globe_tex[GLOBE_TEX_W * GLOBE_TEX_H] = {\n')
        for i in range(0, len(tex), 16):
            f.write(','.join('0x%04x' % t for t in tex[i:i + 16]) + ',\n')
        f.write('};\n\n')
        f.write('const uint8_t globe_ocean[GLOBE_TEX_W * GLOBE_TEX_H / 8] = {\n')
        for i in range(0, len(ocean), 32):
            f.write(','.join('0x%02x' % b for b in ocean[i:i + 32]) + ',\n')
        f.write('};\n')
    print('wrote %s and %s: %d KB texture + %d KB ocean mask' %
          (OUT_H, OUT_C, len(tex) * 2 // 1024, len(ocean) // 1024))


if __name__ == '__main__':
    main()
